project:
  type: book
  preview:
    port: 15745
    browser: false

metadata-files:
  - about.yml

book:
  downloads:
    - docx
  repo-url: https://github.com/MontyBitto/Quarto_Pica/
  repo-actions:
    - source
    - edit
    - issue
  chapters:
    - index.md
    - grundlagen.qmd
    - formate.qmd
    - darstellung.qmd
    - verarbeitung.qmd
    - picadata.qmd
    - catmandu.qmd
    - pica-rs.qmd
    - schnittstellen.qmd
    - bearbeitung.qmd
    - ausblick.qmd
    - CONTRIBUTING.qmd
    - literatur.md
  sidebar:
    style: docked
    logo: img/gbv-vzg-logo.png
  page-footer: 
    left: 
      - text: CC BY 3.0 DE
        href: https://creativecommons.org/licenses/by/3.0/de/
    right: 
      - text: Datenschutz
        href: https://www.gbv.de/datenschutz
      - text: hosted by VZG
        href: https://www.gbv.de/impressum
      - icon: github
        href: https://github.com/MontyBitto/Quarto_Pica/
      - text: "![](img/quarto-badge.svg)"
        href: https://quarto.org
  favicon: img/gbv-vzg-logo.png

bibliography: references.bib 
nocite: |
  @*
tbl-cap-location: bottom
number-sections: false
number-depth: 2

format:
  html:
    theme: cosmo
    css: style.css
    link-external-icon: true
    email-obfuscation: javascript
    callout-appearance: simple
    published-title: "Letzte Änderung"
    number-sections: true
    number-depth: 2
    twitter-card: true
  docx:
    number-sections: true
    number-depth: 2

